import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/Navbar/page";
import Footer from "./components/footer/page";
import AuthProvider from "./components/Auth/AuthProvider/page";
import HideFooter from "./components/HideFooter/page";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <NavBar></NavBar>
          <div className="pt-20">
            {children}
          </div>
          <HideFooter>
            <Footer />
          </HideFooter>
        </AuthProvider>
      </body>
    </html>
  );
}
